version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init-user-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - authstack
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    links:
      - database
    networks:
      - authstack
    ports:
    - "8081:8081"
volumes:
  data:
networks:
  authstack:
    driver: bridge
